### ISSUE TITLE
add a model to an ASP.NET Core MVC app

### ISSUE THREAD

**Issue by ornwipa** [ornwipa/ComITpractice#1]
Follow the guideline in docs.microsoft.com to add model classes for managing movies in a database.

**Comment by ornwipa** [comment]
Use the scaffolding tool to produce Create, Read, Update, and Delete (CRUD) pages for the movie model.

When running... `$ dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries`

Error occurs...
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.StringComparer.get_OrdinalIgnoreCase()
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.ToolCommandLineHelper.IsNoBuild(System.String[])
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.Main(System.String[])
```

**Comment by ornwipa** [comment]
Use the EF Core Migrations feature to create and update the database. 

When running... `dotnet ef migrations add InitialCreate` and `dotnet ef database update`

Error occurs...
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.String, System.Reflection.Assembly)
   at Microsoft.EntityFrameworkCore.Tools.Properties.Resources..cctor()
   at Microsoft.EntityFrameworkCore.Tools.Properties.Resources.GetString(System.String, System.String[])
   at Microsoft.EntityFrameworkCore.Tools.Properties.Resources.get_DotnetEfFullName()
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Configure(Microsoft.DotNet.Cli.CommandLine.CommandLineApplication)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(System.String[])
```

**Comment by ornwipa** [comment]
Some (trial?) fixes at .csproj ... [https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization),
... and [https://talk.remobjects.com/t/how-do-i-enable-net-core-globalization-invariant-mode/18163](https://talk.remobjects.com/t/how-do-i-enable-net-core-globalization-invariant-mode/18163)

Similar issue ... [https://stackoverflow.com/questions/58215952/asp-net-core-crud-tool-command-not-found-but-actually-installed](https://stackoverflow.com/questions/58215952/asp-net-core-crud-tool-command-not-found-but-actually-installed)

This issue might not be solved ... As mentioned in [https://stackoverflow.com/questions/61701254/developing-net-core-in-ubuntu-using-vs-code](https://stackoverflow.com/questions/61701254/developing-net-core-in-ubuntu-using-vs-code), this an incompatibility between .NET Core and Ubuntu 20.04.

**Comment by ornwipa** [comment]
SUCCESS: creating/updating database with EF Core Migration feature
FAIL: scaffolding tool `aspnet-codegenerator` for CRUD page
Error message ...
```
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
A file matching the name MvcControllerWithContext.cshtml was not found within any of the folders: 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

**Comment by ornwipa** [comment]
Manually coded MoviesController.cs & its dependency injection
Switch the entire MvcMovie application to run on Ubuntu 18.04
